### ISSUE TITLE
Unable to load the ergoCubSN001 model

### ISSUE THREAD

**Issue by GiulioRomualdi** [ami-iit/blend-my-bot#3]
I tried to start the example script with `ergoCubSN001` however the loaded model had some issue

![image](https://github.com/ami-iit/blend-my-bot/assets/16744101/5d6c3aa3-38d8-4f38-b60a-c275e2630a04)

On the other hand `ergoCubSN000` works fine

![image](https://github.com/ami-iit/blend-my-bot/assets/16744101/4690245a-c668-4fe8-8d35-395ba73ef05e)

**Comment by Giulero** [comment]
Hi @GiulioRomualdi! Thanks for the issue! Can you try to load again the model?

I'm able to load the model
![image](https://github.com/ami-iit/blend-my-bot/assets/29798643/59cf87ea-50f5-4276-951d-ea6a3891b09f)

**Comment by GiulioRomualdi** [comment]
I retried to load the model and it works as expected. I don't know why I experienced the problem
